
USE BD_FINTECH
GO

SELECT ID_USUARIO, NOME, CPF, EMAIL, SENHA, TIPO_USUARIO, 
CONVERT(VARCHAR, DATA_CRIACAO, 103) AS DATA_CRIACAO 
FROM USUARIO
GO

-- Consultar todos os usuários
SELECT ID_USUARIO, NOME, CPF, EMAIL, SENHA, TIPO_USUARIO, 
CONVERT(VARCHAR, DATA_CRIACAO, 103) AS DATA_CRIACAO 
FROM USUARIO
GO

-- Consultar todas as contas
SELECT ID_CONTA, NUMERO_CONTA, AGENCIA, TIPO_CONTA, SALDO, 
CONVERT(VARCHAR, DATA_ABERTURA, 103) AS DATA_ABERTURA 
FROM CONTA
GO

-- Consultar todas as contas por CPF
SELECT u.NOME, u.CPF, c.ID_CONTA, c.NUMERO_CONTA, c.AGENCIA, c.TIPO_CONTA, c.SALDO, 
CONVERT(VARCHAR, c.DATA_ABERTURA, 103) AS DATA_ABERTURA 
FROM CONTA c INNER JOIN USUARIO u ON u.ID_USUARIO = c.ID_USUARIO
GO

-- CONSULTA DE CONTAS COM CPF
SELECT 
u.NOME, u.CPF, c.ID_CONTA, 
c.NUMERO_CONTA, c.AGENCIA, 
CASE c.TIPO_CONTA
WHEN 1 THEN 'SIMPLES'
WHEN 2 THEN 'PREMIUM'
END AS TIPO_CONTA,
c.SALDO, c.DATA_ABERTURA 
FROM CONTA c INNER JOIN USUARIO u ON u.ID_USUARIO = c.ID_USUARIO

SELECT * FROM BOLETO


-- Consulta de USUÁRIOS e ENDEREÇOS
SELECT 
u.NOME, u.CPF, u.EMAIL,
e.CEP, e.LOGRADOURO, e.NUMERO, e.BAIRRO, 
e.CIDADE, e.ESTADO, e.UF
FROM USUARIO u INNER JOIN ENDERECO e 
ON u.ID_USUARIO = e.ID_USUARIO


-- Consultar todas as transações
SELECT ID_TRANSACAO, TIPO_TRANSACAO, VALOR, DESCRICAO, 
CONVERT(VARCHAR, DATA_TRANSACAO, 103) AS DATA_TRANSACAO 
FROM TRANSACAO
GO

-- Consultar todas as tarifas
SELECT ID_TARIFA, ID_TRANSACAO, VALOR_TARIFA, 
CONVERT(VARCHAR, DATA_TARIFA, 103) AS DATA_TARIFA 
FROM TARIFA
GO

-- Consultar todos os boletos
SELECT 
    t.ID_TRANSACAO,
    b.ID_BOLETO,
	b.CODIGO_BOLETO,
	t.VALOR,
	t.TIPO_TRANSACAO, -- DEIXA TIPO TRANSACAO?
	CONVERT(VARCHAR, DATA_VENCIMENTO, 103) AS DATA_VENCIMENTO
FROM TRANSACAO t
INNER JOIN BOLETO b ON t.ID_TRANSACAO = b.ID_TRANSACAO
--WHERE t.TIPO_TRANSACAO = 4; 

-- Consultar todos os investimentos
SELECT * FROM INVESTIMENTO

-- Consultar todas as aplicações
SELECT ID_APLICACAO, VALOR_APLICACAO, ID_INVESTIMENTO, ID_CONTA,
CONVERT(VARCHAR, DATA_APLICACAO, 103) AS DATA_APLICACAO, 
CONVERT(VARCHAR, DATA_VENCIMENTO, 103) AS DATA_VENCIMENTO 
FROM APLICACAO
GO

-- Consulta do extrato da conta de origem(débito)
SELECT 
    t.ID_TRANSACAO,
    t.VALOR,
    p.CHAVE_PIX,
    co.NUMERO_CONTA AS CONTA,
    'Débito' AS TIPO_OPERACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 103) AS DATA_TRANSACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 108) AS HORA
FROM 
    TRANSACAO t
INNER JOIN PIX p ON t.ID_TRANSACAO = p.ID_TRANSACAO
INNER JOIN CONTA co ON t.ID_CONTA = co.ID_CONTA
-- WHERE co.NUMERO_CONTA = '12345677'; -- número de conta específico
GO

-- Consulta do extrato da conta destino(crédito)
SELECT 
    t.ID_TRANSACAO,
    t.VALOR,
    p.CHAVE_PIX,
    c.NUMERO_CONTA AS CONTA,
    'Crédito' AS TIPO_OPERACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 103) AS DATA_TRANSACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 108) AS HORA
FROM 
    TRANSACAO t
INNER JOIN PIX p ON t.ID_TRANSACAO = p.ID_TRANSACAO
INNER JOIN CONTA c ON t.ID_CONTA_DESTINO = c.ID_CONTA
--WHERE cd.NUMERO_CONTA = '28948238'; -- número de conta específico
GO

-- Consulta saldo total por usuário
SELECT NOME, SUM(c.SALDO) AS SALDO_TOTAL
FROM USUARIO u
INNER JOIN CONTA c ON u.ID_USUARIO = c.ID_USUARIO
GROUP BY u.NOME
GO


-- CONSULTA SALDO TOTAL INDIVIDUAL
SELECT NOME, c.SALDO FROM USUARIO u INNER JOIN CONTA c ON u.ID_USUARIO = c.ID_USUARIO
where u.CPF = 85538353087


-- Consulta valor total investido
SELECT SUM(VALOR_APLICACAO) AS VALOR_TOTAL_INVESTIDO
FROM APLICACAO
GO

-- Consulta dos investimentos por cliente
SELECT NOME, NOME_INVESTIMENTO, SUM(VALOR_APLICACAO) AS VALOR_TOTAL
FROM USUARIO u
INNER JOIN CONTA c ON u.ID_USUARIO = c.ID_USUARIO
INNER JOIN APLICACAO a ON c.ID_CONTA = a.ID_CONTA
INNER JOIN INVESTIMENTO i ON a.ID_INVESTIMENTO = i.ID_INVESTIMENTO
GROUP BY u.NOME, i.NOME_INVESTIMENTO;
GO

-- Consulta da transação por um usuário
SELECT * FROM TRANSACAO
WHERE ID_CONTA = 1
GO-- EXTRATO DTOSELECT 	c.ID_CONTA, 	c.NUMERO_CONTA, 	c.AGENCIA, 	t.ID_TRANSACAO, 		CASE t.TIPO_TRANSACAO			WHEN 1 THEN 'SAQUE'			WHEN 2 THEN 'DEPÓSITO'			WHEN 3 THEN 'PIX'			WHEN 4 THEN 'BOLETO'		END AS TIPO,	t.VALOR, 	t.DATA_TRANSACAO,	t.DESCRICAO	FROM CONTA c INNER JOIN TRANSACAO t 	ON c.ID_CONTA = t.ID_CONTA WHERE c.ID_CONTA = 1GO-- CONSULTA DE TRANSAÇÃO E BOLETO --SELECT  b.ID_BOLETO, b.CODIGO_BOLETO, b.DATA_VENCIMENTO, t.DESCRICAO, t.VALORFROM BOLETO b INNER JOIN TRANSACAO t ON  b.ID_TRANSACAO = t.ID_TRANSACAO;select * from TRANSACAOselect * from BOLETO-- VERIFICAR SE BOLETO EXISTE --	IF EXISTS (SELECT 1 FROM BOLETO WHERE ID_BOLETO = 2)BEGINSELECT * FROM BOLETO WHERE ID_BOLETO = 2ENDselect * from conta