USE BD_FINTECH
GO

-- ALTER TABLES DO BD_FINTECH --

-- TABELA USUARIO - COLOCAR CPF COMO VALOR ÚNICO --
ALTER TABLE USUARIO
ADD CONSTRAINT UK_CPF UNIQUE (CPF)
GO

-- TABELA ADMIN - ADICIONAR 'ID_USUARIO' DA TABELA 'CONTA' COMO FK
ALTER TABLE ADMINISTRADOR
ADD ID_USUARIO INT
GO
ALTER TABLE ADMINISTRADOR
ADD CONSTRAINT FK_ADMIN
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) 
GO

-- TABELA ADMIN - ADICIONAR ATRIBUTOS DE E-MAIL E SENHA NA TABELA ADMIN --
ALTER TABLE ADMINISTRADOR
ADD EMAIL VARCHAR(80) NOT NULL
GO
ALTER TABLE ADMINISTRADOR
ADD SENHA VARCHAR(80) NOT NULL
GO

-- TABELA ADMIN - TRANSFORMAR NUMERO_CONTA EM CAMPO NULL (PORQUE DEU PROBLEMAS COM O JAVA) --
ALTER TABLE CONTA ALTER COLUMN NUMERO_CONTA INT NULL;



ALTER TABLE TRANSACAO
ADD ID_CONTA_ORIGEM INT NOT NULL
    FOREIGN KEY (ID_CONTA_ORIGEM) REFERENCES CONTA(ID_CONTA)
GO
ALTER TABLE TRANSACAO
ADD ID_CONTA_DESTINO INT NOT NULL
    FOREIGN KEY (ID_CONTA_DESTINO) REFERENCES CONTA(ID_CONTA)
GO

-- EXCLUSÃO DA ID_CONTA_ORIGEM E ID_CONTA_DESTINO
ALTER TABLE TRANSACAO DROP COLUMN ID_CONTA_DESTINO
ALTER TABLE TRANSACAO DROP COLUMN ID_CONTA_ORIGEM

ALTER TABLE TRANSACAO
DROP CONSTRAINT FK__TRANSACAO__ID_CO__4BAC3F29;
ALTER TABLE TRANSACAO
DROP CONSTRAINT FK__TRANSACAO__ID_CO__4CA06362;

-- COLOCAR COMO VALOR ÚNICO O COD_BOLETO -- 
ALTER TABLE BOLETO
ADD CONSTRAINT UNQ_CODIGO_BOLETO UNIQUE (CODIGO_BOLETO)
GO

-- COLOCANDO BOLETO COM ID_TRANSACAO NÃO OBRIGATÓRIO E COLUNA DE STATUS_BOLETO --

ALTER TABLE BOLETO
ADD ID_TRANSACAO INT NULL
FOREIGN KEY (ID_TRANSACAO) REFERENCES TRANSACAO(ID_TRANSACAO)

ALTER TABLE BOLETO
ADD STATUS_BOLETO INT DEFAULT 0  -- 0: NÃO PAGO, 1: PAGO PARCIALMENTE, 2: PAGO

SELECT * FROM  BOLETO
