-- Banco de dados do projeto FinTECH
USE BD_FINTECH
GO

CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL IDENTITY(1,1),
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    SENHA VARCHAR(50) NOT NULL,
    TIPO_USUARIO SMALLINT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    PRIMARY KEY(ID_USUARIO),
    CHECK(LEN(CPF) = 11),
    CHECK(TIPO_USUARIO = 1 OR TIPO_USUARIO = 2) -- 1: CLIENTE, 2: ADM
)
GO
ALTER TABLE USUARIO
ADD CONSTRAINT UK_CPF UNIQUE (CPF)
GO

CREATE TABLE ADMINISTRADOR (
	ID_ADMINISTRADOR INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL,
	--SENHA VARCHAR(80) NOT NULL,
	--EMAIL VARCHAR(80) NOT NULL,
	PRIMARY KEY(ID_ADMINISTRADOR)
)
GO
ALTER TABLE ADMINISTRADOR
ADD ID_USUARIO INT
GO
ALTER TABLE ADMINISTRADOR
ADD CONSTRAINT FK_ADMIN
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) 
GO
ALTER TABLE ADMINISTRADOR
ADD EMAIL VARCHAR(80) NOT NULL
GO
ALTER TABLE ADMINISTRADOR
ADD SENHA VARCHAR(80) NOT NULL
GO

CREATE TABLE CONTA (
    ID_USUARIO INT NOT NULL,
    ID_CONTA INT NOT NULL IDENTITY(1,1),
    NUMERO_CONTA INT NOT NULL UNIQUE,
    AGENCIA INT NOT NULL,
    TIPO_CONTA SMALLINT NOT NULL,
    SALDO DECIMAL(10,2) NOT NULL,
    DATA_ABERTURA DATETIME,
    PRIMARY KEY(ID_CONTA),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CHECK(SALDO >= 0),
    CHECK(TIPO_CONTA = 1 OR TIPO_CONTA = 2) -- 1: SIMPLES, 2: PREMIUM
)
GO

CREATE TABLE TRANSACAO (
    ID_TRANSACAO INT NOT NULL IDENTITY(1,1),
    TIPO_TRANSACAO SMALLINT NOT NULL,
    VALOR DECIMAL NOT NULL,
    DATA_TRANSACAO DATETIME NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    ID_CONTA INT,
    PRIMARY KEY(ID_TRANSACAO),
    FOREIGN KEY(ID_CONTA) REFERENCES CONTA(ID_CONTA),
    CHECK(VALOR > 0),
    CHECK(TIPO_TRANSACAO BETWEEN 0 AND 4) -- 0:TRANSFERÊNCIA SUJEITA A TARIFAS , 1:SAQUE , 2:DEPÓSITO , 3:PIX , 4:BOLETO
)
GO
--ALTER TABLE TRANSACAO
--ADD HORA TIME NOT NULL
--GO
ALTER TABLE TRANSACAO
ADD ID_CONTA_ORIGEM INT NOT NULL
    FOREIGN KEY (ID_CONTA_ORIGEM) REFERENCES CONTA(ID_CONTA)
GO
ALTER TABLE TRANSACAO
ADD ID_CONTA_DESTINO INT NOT NULL
    FOREIGN KEY (ID_CONTA_DESTINO) REFERENCES CONTA(ID_CONTA)
GO

CREATE TABLE TARIFA (
    ID_TARIFA INT NOT NULL IDENTITY(1,1),
    ID_TRANSACAO INT NOT NULL,
    VALOR_TARIFA DECIMAL,
    DATA_TARIFA DATETIME NOT NULL,
    PRIMARY KEY(ID_TARIFA),
    FOREIGN KEY(ID_TRANSACAO) REFERENCES TRANSACAO(ID_TRANSACAO)
)
GO

CREATE TABLE BOLETO (
    ID_BOLETO INT NOT NULL IDENTITY(1,1),
    CODIGO_BOLETO VARCHAR(100) UNIQUE NOT NULL,
    DATA_VENCIMENTO DATETIME NOT NULL,
    ID_TRANSACAO INT NOT NULL,
    PRIMARY KEY(ID_BOLETO),
    FOREIGN KEY (ID_TRANSACAO) REFERENCES TRANSACAO(ID_TRANSACAO)
)
GO
ALTER TABLE BOLETO
ADD CONSTRAINT UNQ_CODIGO_BOLETO UNIQUE (CODIGO_BOLETO)
GO

CREATE TABLE PIX (
    ID_PIX INT NOT NULL IDENTITY(1,1),
    CHAVE_PIX VARCHAR(100) NOT NULL,
    TIPO_CHAVE SMALLINT NOT NULL, -- 1: CPF, 2: CNPJ, 3: EMAIL, 4: TELEFONE, 5: CHAVE ALEATÓRIA
    DATA_CRIACAO DATETIME NOT NULL,
    ID_TRANSACAO INT NOT NULL,
    PRIMARY KEY(ID_PIX),
    FOREIGN KEY(ID_TRANSACAO) REFERENCES TRANSACAO(ID_TRANSACAO)
)
GO

CREATE TABLE INVESTIMENTO (
    ID_INVESTIMENTO INT NOT NULL IDENTITY(1,1),
    NOME_INVESTIMENTO VARCHAR(100) NOT NULL,
    RENDIMENTO DECIMAL NOT NULL,
    PRIMARY KEY(ID_INVESTIMENTO),
    CHECK (RENDIMENTO > 0)
)
GO

CREATE TABLE APLICACAO (
    ID_APLICACAO INT NOT NULL IDENTITY(1,1),
    VALOR_APLICACAO DECIMAL NOT NULL,
    DATA_APLICACAO DATETIME NOT NULL,
    DATA_VENCIMENTO DATETIME NOT NULL,
    ID_INVESTIMENTO INT NOT NULL,
    ID_CONTA INT NOT NULL,
    PRIMARY KEY(ID_APLICACAO),
    CHECK (VALOR_APLICACAO > 0),
    FOREIGN KEY (ID_INVESTIMENTO) REFERENCES INVESTIMENTO(ID_INVESTIMENTO),
    FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA)
)
GO

USE BD_FINTECH
GO

-- Inserindo dados na tabela USUARIO
INSERT INTO USUARIO (NOME, CPF, EMAIL, SENHA, TIPO_USUARIO, DATA_CRIACAO) VALUES
('Matheus Santos Ferreira', '85538353087', 'matheusferreira@gmail.com', 'matheus1234','2', GETDATE()),
('Maria Souza Barbosa', '52303220041', 'mariasouza@gmail.com', 'maria1234', '2', GETDATE()),
('Bianca Lima da Silva', '77525442053', 'biancalima@gmail.com', 'bianca@1234', '1', GETDATE())
GO

-- Inserindo dados na tabela ADMINISTRADOR
INSERT INTO ADMINISTRADOR (NOME, SENHA, EMAIL) VALUES
('João Paulo Almeida', 'joao@1234', 'joao.almeida@gmail.com')
GO

-- Inserindo dados na tabela CONTA
INSERT INTO CONTA (ID_USUARIO, NUMERO_CONTA, AGENCIA, TIPO_CONTA, SALDO, DATA_ABERTURA) VALUES
(1, 12345677, 1221, 1, 2500.90, '2024-12-10'),
(2, 28948238, 4433, 2, 1000.50, '2024-12-16')
GO


-- Inserindo dados na tabela TARIFA
INSERT INTO TARIFA (ID_TRANSACAO, VALOR_TARIFA, DATA_TARIFA) VALUES 
(1, 4.00, '2025-01-01'),
(3, 3.00, '2024-12-20')
GO

-- Inserindo dados na tabela BOLETO
INSERT INTO BOLETO (ID_TRANSACAO, CODIGO_BOLETO, DATA_VENCIMENTO) VALUES 
(3, '294948906830748006423700', '2025-01-10')
GO

-- Inserindo dados na tabela TRANSACAO
INSERT INTO TRANSACAO (TIPO_TRANSACAO, VALOR, DATA_TRANSACAO, DESCRICAO, ID_CONTA_ORIGEM, ID_CONTA_DESTINO) VALUES 
(0, 150.00, '2025-01-01', 'Transferência para Maria', 1, 2),
(2, 200.00, '2024-12-20', 'Depósito na conta de Matheus', 2, 1),
(4, 300.00, GETDATE(), 'Pagamento do boleto', 1, 2),
(3, 50.00, GETDATE(), 'Pix para Maria', 1, 2)
GO


-- Inserindo dados na tabela PIX
INSERT INTO PIX (ID_TRANSACAO, CHAVE_PIX, TIPO_CHAVE, DATA_CRIACAO) VALUES
(6, '26932909022', 1, '2025-01-03'),
(2, '11912345678', 1,'2025-01-05'),
(4, 'mariasouza@gmail.com', 3, '2025-01-02'),
(5, 'vM(hdfUF!nkGmv}S6ow', 5, '2025-01-03')
GO

-- Inserindo dados na tabela INVESTIMENTO
INSERT INTO INVESTIMENTO (NOME_INVESTIMENTO, RENDIMENTO) VALUES
('Tesouro Direto', 5.00)
GO

-- Inserindo dados na tabela APLICACAO
INSERT INTO APLICACAO (VALOR_APLICACAO, DATA_APLICACAO, DATA_VENCIMENTO, ID_INVESTIMENTO, ID_CONTA) VALUES
(400.00, '2024-12-22', '2025-02-21', 1, 1)



USE BD_FINTECH
GO

-- Consultar todos os usuários
SELECT ID_USUARIO, NOME, CPF, EMAIL, SENHA, TIPO_USUARIO, 
CONVERT(VARCHAR, DATA_CRIACAO, 103) AS DATA_CRIACAO 
FROM USUARIO
GO

-- Consultar todas as contas
SELECT ID_CONTA, NUMERO_CONTA, AGENCIA, TIPO_CONTA, SALDO, 
CONVERT(VARCHAR, DATA_ABERTURA, 103) AS DATA_ABERTURA 
FROM CONTA
GO

-- Consultar todas as transações
SELECT ID_TRANSACAO, TIPO_TRANSACAO, VALOR, DESCRICAO, ID_CONTA_ORIGEM, ID_CONTA_DESTINO, 
CONVERT(VARCHAR, DATA_TRANSACAO, 103) AS DATA_TRANSACAO 
FROM TRANSACAO
GO

-- Consultar todas as tarifas
SELECT ID_TARIFA, ID_TRANSACAO, VALOR_TARIFA, 
CONVERT(VARCHAR, DATA_TARIFA, 103) AS DATA_TARIFA 
FROM TARIFA
GO

-- Consultar todos os boletos
SELECT 
    t.ID_TRANSACAO,
    b.ID_BOLETO,
	b.CODIGO_BOLETO,
	t.VALOR,
	t.TIPO_TRANSACAO, -- DEIXA TIPO TRANSACAO?
	CONVERT(VARCHAR, DATA_VENCIMENTO, 103) AS DATA_VENCIMENTO
FROM TRANSACAO t
INNER JOIN BOLETO b ON t.ID_TRANSACAO = b.ID_TRANSACAO
--WHERE t.TIPO_TRANSACAO = 4; 

-- Consultar todos os investimentos
SELECT * FROM INVESTIMENTO

-- Consultar todas as aplicações
SELECT ID_APLICACAO, VALOR_APLICACAO, ID_INVESTIMENTO, ID_CONTA,
CONVERT(VARCHAR, DATA_APLICACAO, 103) AS DATA_APLICACAO, 
CONVERT(VARCHAR, DATA_VENCIMENTO, 103) AS DATA_VENCIMENTO 
FROM APLICACAO
GO


-- Consulta do extrato da conta de origem(débito)
SELECT 
    t.ID_TRANSACAO,
    t.VALOR,
    p.CHAVE_PIX,
    co.NUMERO_CONTA AS CONTA,
    'Débito' AS TIPO_OPERACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 103) AS DATA_TRANSACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 108) AS HORA
FROM 
    TRANSACAO t
INNER JOIN PIX p ON t.ID_TRANSACAO = p.ID_TRANSACAO
INNER JOIN CONTA co ON t.ID_CONTA_ORIGEM = co.ID_CONTA
-- WHERE co.NUMERO_CONTA = '12345677'; -- número de conta específico
GO

-- Consulta do extrato da conta destino(crédito)
SELECT 
    t.ID_TRANSACAO,
    t.VALOR,
    p.CHAVE_PIX,
    c.NUMERO_CONTA AS CONTA,
    'Crédito' AS TIPO_OPERACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 103) AS DATA_TRANSACAO,
	CONVERT(VARCHAR, t.DATA_TRANSACAO, 108) AS HORA
FROM 
    TRANSACAO t
INNER JOIN PIX p ON t.ID_TRANSACAO = p.ID_TRANSACAO
INNER JOIN CONTA c ON t.ID_CONTA_DESTINO = c.ID_CONTA
--WHERE cd.NUMERO_CONTA = '28948238'; -- número de conta específico
GO

-- Consulta saldo total por usuário
SELECT NOME, SUM(c.SALDO) AS SALDO_TOTAL
FROM USUARIO u
INNER JOIN CONTA c ON u.ID_USUARIO = c.ID_USUARIO
GROUP BY u.NOME
GO

-- Consulta valor total investido
SELECT SUM(VALOR_APLICACAO) AS VALOR_TOTAL_INVESTIDO
FROM APLICACAO
GO

-- Consulta dos investimentos por cliente
SELECT NOME, NOME_INVESTIMENTO, SUM(VALOR_APLICACAO) AS VALOR_TOTAL
FROM USUARIO u
INNER JOIN CONTA c ON u.ID_USUARIO = c.ID_USUARIO
INNER JOIN APLICACAO a ON c.ID_CONTA = a.ID_CONTA
INNER JOIN INVESTIMENTO i ON a.ID_INVESTIMENTO = i.ID_INVESTIMENTO
GROUP BY u.NOME, i.NOME_INVESTIMENTO;
GO

-- Consulta da transação por um usuário
SELECT * FROM TRANSACAO
WHERE ID_CONTA_ORIGEM = 2
GO
